CREATE TABLE IF NOT EXISTS prospects (
	id SERIAL PRIMARY KEY,
	first_name TEXT,
	last_name TEXT,
	title TEXT,
	company_name TEXT,
	email TEXT,
	email_status TEXT,
	primary_email_source TEXT,
	primary_email_verification_source TEXT,
	email_confidence TEXT,
	primary_email_catchall_status TEXT,
	primary_email_last_verified_at TEXT,
	seniority TEXT,
	sub_departments TEXT,
	work_direct_phone TEXT,
	home_phone TEXT,
	mobile_phone TEXT,
	corporate_phone TEXT,
	other_phone TEXT,
	do_not_call TEXT,
	lists TEXT,
	person_linkedin_url TEXT,
	country TEXT,
	subsidiary_of TEXT,
	subsidiary_of_organization_id TEXT,
	tertiary_email TEXT,
	tertiary_email_source TEXT,
	tertiary_email_status TEXT,
	tertiary_email_verification_source TEXT,
	primary_intent_topic TEXT,
	primary_intent_score TEXT,
	secondary_intent_topic TEXT,
	secondary_intent_score TEXT,
	qualify_contact TEXT,
	cleaned TEXT,
	search_vector TSVECTOR,
	flag BOOLEAN DEFAULT FALSE,
	hide BOOLEAN DEFAULT FALSE
);
